name: Discord Commit Notifier

on:
  push:
    branches:
      - dev
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "<@1385479196247330937> A new commit has been pushed"
