name: Discord Commit Notifier

on:
  push:
    branches:
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: "<@&1385479196247330937> A new commit has been pushed to the dev branch\nhttps://github.com/${{ github.repository }}"
